language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

env:
  global:
    - MONGO_DATABASE=my_database
    - MONGO_COLLECTION=my_collection
    - MONGO_URI=mongodb://localhost:27017/my_database

sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Work around fix for buffer overflow error on OpenJDK7
# ref: https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
  - sudo mv /tmp/hosts /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  - sudo apt-get update
  - sudo apt-get install -y --force-yes mongodb-org
  - mongod -version
  - curl --create-dirs -o ~/.embulk/bin/embulk -L "https://dl.bintray.com/embulk/maven/embulk-0.8.8.jar"
  - chmod +x ~/.embulk/bin/embulk
  - export PATH="$HOME/.embulk/bin:$PATH"
  - embulk --version

before_script:
  - echo "Wait mongodb wakeup"
  - sleep 15
  - mkdir -p ./tmp
  - date

script:
  - ./gradlew check
  - ./gradlew package
  - mongoimport --host 127.0.0.1 --db $MONGO_DATABASE --collection $MONGO_COLLECTION --type json --drop src/test/resources/my_collection.jsonl
  - |
    for target in basic full id_field_name
    do
      embulk run -L . src/test/resources/${target}.yml
      cat tmp/${target}000.00.csv
      cmp tmp/${target}000.00.csv src/test/resources/${target}_expected.csv
    done
